# Generated by Django 5.0.3 on 2024-03-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_page_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_burner_image', models.ImageField(blank=True, null=True, upload_to='aboutpage/images')),
                ('about_title', models.CharField(blank=True, max_length=300)),
                ('about_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300)),
                ('blog_subtitle', models.CharField(max_length=300)),
                ('posted_by', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Page_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_burner_image', models.ImageField(blank=True, null=True, upload_to='contactpage/images')),
                ('contact_title', models.CharField(blank=True, max_length=300)),
                ('contact_description', models.CharField(blank=True, max_length=300)),
                ('contact_paragraph', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Home_page_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_burner_image', models.ImageField(blank=True, null=True, upload_to='homepage/images')),
                ('home_title', models.CharField(blank=True, max_length=300)),
                ('home_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
